server:
  port: 8081
spring:
  #아래는 jdbc의 기본 db 연결 설정. jdbc뿐만 아니라, mybatis, jpa등 spring의 대부분의 db 관리기술에서 사용.
  #스키마는 사전 생성 필요, 테이블의 경우 jdbc/mybatis는 사전생성 필요.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: test1234
  jpa:
    database: mysql
    #    innoDB를 쓰겠다는 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    밑에서부터 중요한 설정구리
    #    ddl문(테이블생성) 자동생성 여부 : true
    generate-ddl: true
    #    jpa(인터페이스 명세)의 실질적인 구현체는 hibernate
    hibernate:
      #      ddl문 자동생성에 대한 모드(create, update, validate)(레벨)설정 사고나는 지점(정확히)
      #      create : 매번(서버재시작마다) table을 전체 drop후 재생성(실무에서 환경설정건들지말기) - 프로젝트최초구성시
      #      update : 엔티티의 변경사항만 alter를 적용. 기존데이터 유지. -개발서버목적
      #      validate : 실제DB와의 차이점을 check만 하고 ddl문 실행X(콘솔에 변경사항만 출력) - 운영서버목적
      ddl-auto: create
    #      콘솔창에 ddl, dml등의 커리르 출력하여 보여주는 옵션
    show_sql: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml